language: minimal

sudo: true

addons:
  apt:
    packages:
    - tidy
    - markdown

script:
- "./builder/builder.sh"

before_install:
- openssl aes-256-cbc -K $encrypted_707d7b8ddfbe_key -iv $encrypted_707d7b8ddfbe_iv -in hedenenterprises_travis.enc -out hedenenterprises_travis -d
